// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: v1/captcha.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientEvent_EventType int32

const (
	ClientEvent_FRONTEND_EVENT        ClientEvent_EventType = 0
	ClientEvent_CONNECTION_CLOSED     ClientEvent_EventType = 1
	ClientEvent_BALANCER_EVENT        ClientEvent_EventType = 2
	ClientEvent_ClOSE_CHALLENGE_EVENT ClientEvent_EventType = 3
)

// Enum value maps for ClientEvent_EventType.
var (
	ClientEvent_EventType_name = map[int32]string{
		0: "FRONTEND_EVENT",
		1: "CONNECTION_CLOSED",
		2: "BALANCER_EVENT",
		3: "ClOSE_CHALLENGE_EVENT",
	}
	ClientEvent_EventType_value = map[string]int32{
		"FRONTEND_EVENT":        0,
		"CONNECTION_CLOSED":     1,
		"BALANCER_EVENT":        2,
		"ClOSE_CHALLENGE_EVENT": 3,
	}
)

func (x ClientEvent_EventType) Enum() *ClientEvent_EventType {
	p := new(ClientEvent_EventType)
	*p = x
	return p
}

func (x ClientEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_captcha_proto_enumTypes[0].Descriptor()
}

func (ClientEvent_EventType) Type() protoreflect.EnumType {
	return &file_v1_captcha_proto_enumTypes[0]
}

func (x ClientEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientEvent_EventType.Descriptor instead.
func (ClientEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_v1_captcha_proto_rawDescGZIP(), []int{2, 0}
}

type ChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Complexity    int32                  `protobuf:"varint,1,opt,name=complexity,proto3" json:"complexity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeRequest) Reset() {
	*x = ChallengeRequest{}
	mi := &file_v1_captcha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeRequest) ProtoMessage() {}

func (x *ChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_captcha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeRequest.ProtoReflect.Descriptor instead.
func (*ChallengeRequest) Descriptor() ([]byte, []int) {
	return file_v1_captcha_proto_rawDescGZIP(), []int{0}
}

func (x *ChallengeRequest) GetComplexity() int32 {
	if x != nil {
		return x.Complexity
	}
	return 0
}

type ChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Html          string                 `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_v1_captcha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_captcha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_v1_captcha_proto_rawDescGZIP(), []int{1}
}

func (x *ChallengeResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ChallengeResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

type ClientEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     ClientEvent_EventType  `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=captcha.v1.ClientEvent_EventType" json:"event_type,omitempty"`
	ChallengeId   string                 `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_v1_captcha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_captcha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_v1_captcha_proto_rawDescGZIP(), []int{2}
}

func (x *ClientEvent) GetEventType() ClientEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return ClientEvent_FRONTEND_EVENT
}

func (x *ClientEvent) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ClientEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServerEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_Result
	//	*ServerEvent_ClientData
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_v1_captcha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_captcha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_v1_captcha_proto_rawDescGZIP(), []int{3}
}

func (x *ServerEvent) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetResult() *ServerEvent_ChallengeResult {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ServerEvent) GetClientData() *ServerEvent_SendClientData {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_ClientData); ok {
			return x.ClientData
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_Result struct {
	Result *ServerEvent_ChallengeResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type ServerEvent_ClientData struct {
	ClientData *ServerEvent_SendClientData `protobuf:"bytes,3,opt,name=client_data,json=clientData,proto3,oneof"`
}

func (*ServerEvent_Result) isServerEvent_Event() {}

func (*ServerEvent_ClientData) isServerEvent_Event() {}

type ServerEvent_ChallengeResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConfidencePercent int32                  `protobuf:"varint,1,opt,name=confidence_percent,json=confidencePercent,proto3" json:"confidence_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServerEvent_ChallengeResult) Reset() {
	*x = ServerEvent_ChallengeResult{}
	mi := &file_v1_captcha_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_ChallengeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_ChallengeResult) ProtoMessage() {}

func (x *ServerEvent_ChallengeResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_captcha_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_ChallengeResult.ProtoReflect.Descriptor instead.
func (*ServerEvent_ChallengeResult) Descriptor() ([]byte, []int) {
	return file_v1_captcha_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ServerEvent_ChallengeResult) GetConfidencePercent() int32 {
	if x != nil {
		return x.ConfidencePercent
	}
	return 0
}

type ServerEvent_SendClientData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_SendClientData) Reset() {
	*x = ServerEvent_SendClientData{}
	mi := &file_v1_captcha_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_SendClientData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_SendClientData) ProtoMessage() {}

func (x *ServerEvent_SendClientData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_captcha_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_SendClientData.ProtoReflect.Descriptor instead.
func (*ServerEvent_SendClientData) Descriptor() ([]byte, []int) {
	return file_v1_captcha_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ServerEvent_SendClientData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_v1_captcha_proto protoreflect.FileDescriptor

var file_v1_captcha_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x76, 0x31, 0x22, 0x32,
	0x0a, 0x10, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x69, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x69,
	0x74, 0x79, 0x22, 0x4a, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6c, 0x6c,
	0x65, 0x6e, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x74,
	0x6d, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x22, 0xed,
	0x01, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x40,
	0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x21, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x65, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x52, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x44,
	0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4e, 0x4e,
	0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x44, 0x10, 0x01, 0x12,
	0x12, 0x0a, 0x0e, 0x42, 0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x52, 0x5f, 0x45, 0x56, 0x45, 0x4e,
	0x54, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x6c, 0x4f, 0x53, 0x45, 0x5f, 0x43, 0x48, 0x41,
	0x4c, 0x4c, 0x45, 0x4e, 0x47, 0x45, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x03, 0x22, 0xaf,
	0x02, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x49,
	0x64, 0x12, 0x41, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c,
	0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x49, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x61, 0x70, 0x74,
	0x63, 0x68, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x1a,
	0x40, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65,
	0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e,
	0x74, 0x1a, 0x24, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x32, 0xaa, 0x01, 0x0a, 0x0e, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x12, 0x1c, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x49, 0x0a, 0x0f, 0x4d, 0x61, 0x6b, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x17,
	0x2e, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x11, 0x5a,
	0x0f, 0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x2f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_v1_captcha_proto_rawDescOnce sync.Once
	file_v1_captcha_proto_rawDescData []byte
)

func file_v1_captcha_proto_rawDescGZIP() []byte {
	file_v1_captcha_proto_rawDescOnce.Do(func() {
		file_v1_captcha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_captcha_proto_rawDesc), len(file_v1_captcha_proto_rawDesc)))
	})
	return file_v1_captcha_proto_rawDescData
}

var file_v1_captcha_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_captcha_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_captcha_proto_goTypes = []any{
	(ClientEvent_EventType)(0),          // 0: captcha.v1.ClientEvent.EventType
	(*ChallengeRequest)(nil),            // 1: captcha.v1.ChallengeRequest
	(*ChallengeResponse)(nil),           // 2: captcha.v1.ChallengeResponse
	(*ClientEvent)(nil),                 // 3: captcha.v1.ClientEvent
	(*ServerEvent)(nil),                 // 4: captcha.v1.ServerEvent
	(*ServerEvent_ChallengeResult)(nil), // 5: captcha.v1.ServerEvent.ChallengeResult
	(*ServerEvent_SendClientData)(nil),  // 6: captcha.v1.ServerEvent.SendClientData
}
var file_v1_captcha_proto_depIdxs = []int32{
	0, // 0: captcha.v1.ClientEvent.event_type:type_name -> captcha.v1.ClientEvent.EventType
	5, // 1: captcha.v1.ServerEvent.result:type_name -> captcha.v1.ServerEvent.ChallengeResult
	6, // 2: captcha.v1.ServerEvent.client_data:type_name -> captcha.v1.ServerEvent.SendClientData
	1, // 3: captcha.v1.CaptchaService.NewChallenge:input_type -> captcha.v1.ChallengeRequest
	3, // 4: captcha.v1.CaptchaService.MakeEventStream:input_type -> captcha.v1.ClientEvent
	2, // 5: captcha.v1.CaptchaService.NewChallenge:output_type -> captcha.v1.ChallengeResponse
	4, // 6: captcha.v1.CaptchaService.MakeEventStream:output_type -> captcha.v1.ServerEvent
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_captcha_proto_init() }
func file_v1_captcha_proto_init() {
	if File_v1_captcha_proto != nil {
		return
	}
	file_v1_captcha_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerEvent_Result)(nil),
		(*ServerEvent_ClientData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_captcha_proto_rawDesc), len(file_v1_captcha_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_captcha_proto_goTypes,
		DependencyIndexes: file_v1_captcha_proto_depIdxs,
		EnumInfos:         file_v1_captcha_proto_enumTypes,
		MessageInfos:      file_v1_captcha_proto_msgTypes,
	}.Build()
	File_v1_captcha_proto = out.File
	file_v1_captcha_proto_goTypes = nil
	file_v1_captcha_proto_depIdxs = nil
}
