// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: v1/waf.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterInstanceRequest_EventType int32

const (
	RegisterInstanceRequest_UNKNOWN   RegisterInstanceRequest_EventType = 0
	RegisterInstanceRequest_READY     RegisterInstanceRequest_EventType = 1
	RegisterInstanceRequest_NOT_READY RegisterInstanceRequest_EventType = 2
	RegisterInstanceRequest_STOPPED   RegisterInstanceRequest_EventType = 3
)

// Enum value maps for RegisterInstanceRequest_EventType.
var (
	RegisterInstanceRequest_EventType_name = map[int32]string{
		0: "UNKNOWN",
		1: "READY",
		2: "NOT_READY",
		3: "STOPPED",
	}
	RegisterInstanceRequest_EventType_value = map[string]int32{
		"UNKNOWN":   0,
		"READY":     1,
		"NOT_READY": 2,
		"STOPPED":   3,
	}
)

func (x RegisterInstanceRequest_EventType) Enum() *RegisterInstanceRequest_EventType {
	p := new(RegisterInstanceRequest_EventType)
	*p = x
	return p
}

func (x RegisterInstanceRequest_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterInstanceRequest_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_waf_proto_enumTypes[0].Descriptor()
}

func (RegisterInstanceRequest_EventType) Type() protoreflect.EnumType {
	return &file_v1_waf_proto_enumTypes[0]
}

func (x RegisterInstanceRequest_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterInstanceRequest_EventType.Descriptor instead.
func (RegisterInstanceRequest_EventType) EnumDescriptor() ([]byte, []int) {
	return file_v1_waf_proto_rawDescGZIP(), []int{0, 0}
}

type RegisterInstanceResponse_Status int32

const (
	RegisterInstanceResponse_SUCCESS RegisterInstanceResponse_Status = 0
	RegisterInstanceResponse_ERROR   RegisterInstanceResponse_Status = 1
)

// Enum value maps for RegisterInstanceResponse_Status.
var (
	RegisterInstanceResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR",
	}
	RegisterInstanceResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   1,
	}
)

func (x RegisterInstanceResponse_Status) Enum() *RegisterInstanceResponse_Status {
	p := new(RegisterInstanceResponse_Status)
	*p = x
	return p
}

func (x RegisterInstanceResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterInstanceResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_waf_proto_enumTypes[1].Descriptor()
}

func (RegisterInstanceResponse_Status) Type() protoreflect.EnumType {
	return &file_v1_waf_proto_enumTypes[1]
}

func (x RegisterInstanceResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterInstanceResponse_Status.Descriptor instead.
func (RegisterInstanceResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_v1_waf_proto_rawDescGZIP(), []int{1, 0}
}

type RegisterInstanceRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	EventType     RegisterInstanceRequest_EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=balancer.v1.RegisterInstanceRequest_EventType" json:"event_type,omitempty"`
	InstanceId    string                            `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ChallengeId   string                            `protobuf:"bytes,3,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Host          string                            `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	PortNumber    int32                             `protobuf:"varint,5,opt,name=port_number,json=portNumber,proto3" json:"port_number,omitempty"`
	Timestamp     int64                             `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterInstanceRequest) Reset() {
	*x = RegisterInstanceRequest{}
	mi := &file_v1_waf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInstanceRequest) ProtoMessage() {}

func (x *RegisterInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInstanceRequest.ProtoReflect.Descriptor instead.
func (*RegisterInstanceRequest) Descriptor() ([]byte, []int) {
	return file_v1_waf_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterInstanceRequest) GetEventType() RegisterInstanceRequest_EventType {
	if x != nil {
		return x.EventType
	}
	return RegisterInstanceRequest_UNKNOWN
}

func (x *RegisterInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterInstanceRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *RegisterInstanceRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterInstanceRequest) GetPortNumber() int32 {
	if x != nil {
		return x.PortNumber
	}
	return 0
}

func (x *RegisterInstanceRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RegisterInstanceResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Status        RegisterInstanceResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=balancer.v1.RegisterInstanceResponse_Status" json:"status,omitempty"`
	Message       string                          `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterInstanceResponse) Reset() {
	*x = RegisterInstanceResponse{}
	mi := &file_v1_waf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInstanceResponse) ProtoMessage() {}

func (x *RegisterInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInstanceResponse.ProtoReflect.Descriptor instead.
func (*RegisterInstanceResponse) Descriptor() ([]byte, []int) {
	return file_v1_waf_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterInstanceResponse) GetStatus() RegisterInstanceResponse_Status {
	if x != nil {
		return x.Status
	}
	return RegisterInstanceResponse_SUCCESS
}

func (x *RegisterInstanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_waf_proto protoreflect.FileDescriptor

var file_v1_waf_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x76, 0x31, 0x2f, 0x77, 0x61, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc0, 0x02, 0x0a,
	0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x6f, 0x72, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x3f,
	0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x41, 0x44,
	0x59, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x03, 0x22,
	0x9c, 0x01, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x20, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x32, 0x78,
	0x0a, 0x0f, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x65, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x24, 0x2e, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x70, 0x62,
	0x2f, 0x77, 0x61, 0x66, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_v1_waf_proto_rawDescOnce sync.Once
	file_v1_waf_proto_rawDescData []byte
)

func file_v1_waf_proto_rawDescGZIP() []byte {
	file_v1_waf_proto_rawDescOnce.Do(func() {
		file_v1_waf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_waf_proto_rawDesc), len(file_v1_waf_proto_rawDesc)))
	})
	return file_v1_waf_proto_rawDescData
}

var file_v1_waf_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_waf_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_waf_proto_goTypes = []any{
	(RegisterInstanceRequest_EventType)(0), // 0: balancer.v1.RegisterInstanceRequest.EventType
	(RegisterInstanceResponse_Status)(0),   // 1: balancer.v1.RegisterInstanceResponse.Status
	(*RegisterInstanceRequest)(nil),        // 2: balancer.v1.RegisterInstanceRequest
	(*RegisterInstanceResponse)(nil),       // 3: balancer.v1.RegisterInstanceResponse
}
var file_v1_waf_proto_depIdxs = []int32{
	0, // 0: balancer.v1.RegisterInstanceRequest.event_type:type_name -> balancer.v1.RegisterInstanceRequest.EventType
	1, // 1: balancer.v1.RegisterInstanceResponse.status:type_name -> balancer.v1.RegisterInstanceResponse.Status
	2, // 2: balancer.v1.BalancerService.RegisterInstance:input_type -> balancer.v1.RegisterInstanceRequest
	3, // 3: balancer.v1.BalancerService.RegisterInstance:output_type -> balancer.v1.RegisterInstanceResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_waf_proto_init() }
func file_v1_waf_proto_init() {
	if File_v1_waf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_waf_proto_rawDesc), len(file_v1_waf_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_waf_proto_goTypes,
		DependencyIndexes: file_v1_waf_proto_depIdxs,
		EnumInfos:         file_v1_waf_proto_enumTypes,
		MessageInfos:      file_v1_waf_proto_msgTypes,
	}.Build()
	File_v1_waf_proto = out.File
	file_v1_waf_proto_goTypes = nil
	file_v1_waf_proto_depIdxs = nil
}
